apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: publish-github-repo
  title: Publish workspace contents to GitHub
  description: Initializes a git repository of contents in workspace and publishes it to GitHub
  tags:
  - github

spec:
  type: service
  parameters:
    - title: Label information
      required: ['repoUrl']
      properties:
        repoUrl:
          title: Repository URL
          type: string
          description: URL of the repository location
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
        token:
          title: Authentication Token
          type: string
          ui:field: Secret
          description: The GITHUB_TOKEN to use for authorization to GitHub

  steps:
    - id: fetchFile
      name: fetch test file
      action: fetch:plain:file
      input:
        url: https://github.com/redhat-developer/red-hat-developer-hub-software-templates/blob/main/README.md
        targetPath: target-path
    - id: publishRepo
      name: Publish workspace contents to GitHub
      action: publish:github
      input:
        repoUrl: ${{ parameters.repoUrl }}
        token: ${{ secrets.token }}

  output:
    links:
      - title: URL to the repository with the provider
        url: ${{ steps.publishRepo.output.remoteUrl }}
      - title: URL to the root of the repository
        url: ${{ steps.publishRepo.output.repoContentsUrl }}
    text:
      - title: The git commit hash of the initial commit
        content: ${{ steps.publishRepo.output.commitHash }}