apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: create-github-repo
  title: Create a GitHub repository
  description: Create a GitHub repository
  tags:
  - github

spec:
  type: service
  parameters:
    - title: Label information
      required: ['repoUrl']
      properties:
        repoUrl:
          title: Repository URL
          type: string
          description: URL of the repository location
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
        token:
          title: Authentication Token
          type: string
          ui:field: Secret
          description: The GITHUB_TOKEN to use for authorization to GitHub

  steps:
    - id: createRepo
      name: Create a GitHub repository
      action: github:repo:create
      input:
        repoUrl: ${{ parameters.repoUrl }}
        token: ${{ secrets.token }}